# Generated by Django 5.0.6 on 2024-06-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicinesAppHandler', '0004_rename_medicines_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
