# Generated by Django 5.0.6 on 2024-06-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicinesAppHandler', '0005_alter_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicinesAppHandler.medicinename'),
        ),
    ]
