# Generated by Django 5.0.6 on 2024-06-18 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicinesAppHandler', '0007_alter_user_email_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
