# Generated by Django 5.0.6 on 2024-06-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
